config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "messages#index"
  resources :users, only: [:index, :edit, :update]
  resources :todos, only: [:index, :create, :destroy]
  resources :memos, only: [:index, :new, :create, :edit, :update, :destroy] do
    collection do
      get :all_destroy
    end
  end
  resources :themes, only: [:index, :new, :create, :edit, :update] do
    resources :posts, only: [:index, :create, :edit, :update]
  end
  resources :newsweeks, only: [:index, :new] do
    collection do
      get :search_title
      get :search_category
      get :test_1
      get :test_2
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/memo.rb
class Memo < ApplicationRecord
end

app/models/newsweek.rb
class Newsweek < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/scraping.rb
class Scraping
  def self.newsweek_urls
    links = []
    agent = Mechanize.new
    for num in 1..15 do
      agent = Mechanize.new
      if (num == 1) then
        url = "https://www.newsweekjapan.jp/stories/index.php"
        links << url
      else 
        url = "https://www.newsweekjapan.jp/stories/index_#{num}.php"
        links << url
      end
    end

    links.each do |link|
      get_article(link)
    end
  end

  def self.get_article(link)
    agent = Mechanize.new
    page = agent.get(link)

    category = []
    title = []
    date = []
    image_url = []
    article_url = []

    category_elements = page.search('.entryTxt .catch')
    title_elements = page.search('.entryTxt h3')
    date_elements = page.search('.entryTxt .date')
    image_elements = page.search('.entryImg img')
    article_elements = page.search('.entry.clearfix.border_btm.containImg a')

    for i in 0..19 do
      category[i] = category_elements[i].inner_text
      title[i] = title_elements[i].inner_text
      date[i] = date_elements[i].inner_text
      image_url[i] = "https://www.newsweekjapan.jp#{image_elements[i].get_attribute('src')}"
      article_url[i] = "https://www.newsweekjapan.jp#{article_elements[i].get_attribute('href')}"
      Newsweek.create(title: title[i], image: image_url[i], url: article_url[i], category: category[i], date: date[i])
    end
  end
end

app/models/theme.rb
class Theme < ApplicationRecord
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController

  def index
    @memos = Memo.order("created_at DESC").all
  end

  def new
    @memo = Memo.new
  end

  def create
    @memo = Memo.create(memo_params)
    redirect_to action: :index
  end

  def edit
    @memo = Memo.find(params[:id])
  end

  def update
    @memo = Memo.find(params[:id])
    @memo.update(memo_params)
    redirect_to action: :index
  end

  def destroy
    @memo = Memo.find(params[:id])
    @memo.destroy
    redirect_to action: :index
  end

  def all_destroy
    Memo.delete_all
    redirect_to action: :index
  end

  private 
  def memo_params
    params.require(:memo).permit(:content)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
  end
end

app/controllers/newsweeks_controller.rb
class NewsweeksController < ApplicationController

  def index
    NewsweekScrapingJobJob.perform_later
    @newsweeks = Newsweek.order('id ASC').page(params[:page]).per(20)
  end

  def new
  end

  def search_title
    @newsweeks = Newsweek.where('title LIKE(?)',"%#{params[:keyword]}%").order('id ASC')
    respond_to do |format|
      format.html
      format.json
    end
  end

  def search_category
    @newsweeks = Newsweek.where('category LIKE(?)',"%#{params[:keyword]}%").order('id ASC')
    respond_to do |format|
      format.html
      format.json
    end
  end

  def test_1
  end

  def test_2
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
  end

  def create
  end

  def edit
  end

  def update
  end
  
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController

  def index
  end

  def new
  end

  def create
  end

  def edit
  end
  
  def update
  end

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

  def index
    @todo = Todo.new
    @todos = Todo.order('created_at ASC')
  end

  def create
    @todo = Todo.new(todo_params)
    if @todo.save
      respond_to do |format|
        format.html { redirect_to todos_path }
        format.json
      end
    else
      render :index
    end
  end

  def destroy
    todo = Todo.find(params[:id])
    todo.destroy
    redirect_to todos_path
  end

  private
  def todo_params
    params.require(:todo).permit(:content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def edit
  end

  def update
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/newsweeks_helper.rb
module NewsweeksHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/memos/_memo.html.haml
.memo{data: {id: "#{memo.id}"}}
  .memo__top
    %p.memo__top__content
      = memo.content
  .memo__bottom
    .memo__bottom__left
      %ul.memo__bottom__left__btns
        %li= link_to "EDIT", edit_memo_path(memo.id), class: "memo__bottom__left__btns__edit-btn btn-sticky"
        %li= link_to "DELETE", memo_path(memo.id), method: :delete, class: "memo__bottom__left__btns__delete-btn btn-sticky"
    %ul.memo__bottom__right
      %li.memo__bottom__right__date
        = memo.created_at.strftime("%Y/%m/%d")
      %li.memo__bottom__right__time
        = memo.created_at.strftime("%H:%M")

app/views/memos/create.html.haml
= link_to 'Back', memos_path

app/views/memos/edit.html.haml
= form_for(@memo, url: "/memos/#{@memo.id}", method: :patch, html: {class: 'memo-form'}) do |f|
  = f.text_area :content, class: "memo-form__text_area"
  = f.submit "Update", class: "memo-form__submit-btn"
  = link_to 'Back', memos_path, class: "memo-form-back"

app/views/memos/index.html.haml
.memo_contents
  %ul.memo_contents__header
    %li= link_to fa_icon("pencil-square-o") + " New Memo", new_memo_path, class: "memo_contents__header__new-memo"
    %li= link_to fa_icon("trash") + " Delete All Memos", all_destroy_memos_path, class: "memo_contents__header__delete-all"
  .memos
    - @memos.each do |memo|
      = render partial: "memo", locals: { memo: memo }

app/views/memos/new.html.haml
= form_for(@memo, url: "/memos", method: :post, html: {class: 'memo-form'}) do |f|
  = f.text_area :content, class: "memo-form__text_area"
  = f.submit "Update", class: "memo-form__submit-btn"
  = link_to 'Back', memos_path, class: "memo-form-back"

app/views/newsweeks/_newsweek_article.html.haml
.article
  = image_tag article.image, class: "article__image"
  %ul.article__items
    %li.category
      = article.category
    %li.title
      = link_to article.title, article.url
    %li.date
      = article.date

app/views/newsweeks/index.html.haml
.newsweeks
  .newsweeks__search-zone 
    %input.newsweeks__search-zone__form#article-title-input{name: "keyword", placeholder: "記事名で検索", type:"text"}  
    %button.newsweeks__search-zone__btn.btn-square-pop#article-category-change{name: "search", type: "submit"}
      カテゴリー名で検索
    %input.newsweeks__search-zone__form#article-category-input{name: "keyword", placeholder: "カテゴリー名で検索", type:"text"}  
    %button.newsweeks__search-zone__btn.btn-square-pop#article-title-change{name: "search", type: "submit"}
      記事名で検索
  .newsweeks__articles
    - @newsweeks.each do |newsweek|
      = render partial: "newsweek_article", locals: { article: newsweek }
  = paginate(@newsweeks)
  

app/views/newsweeks/test_1.html.haml
yes

app/views/newsweeks/test_2.html.haml
no

app/views/themes/_theme.html.haml
.theme
  .more
    .more__image
      = image_tag 'arrow_top.png'
    %ul.more__list#pop
      %li
        = link_to 'テーマ名変更', class: 'more__list__change-theme'
      %li
        = link_to '削除', class: 'more__list__delete'
.theme
  .more
    .more__image
      = image_tag 'arrow_top.png'
    %ul.more__list#pop
      %li
        = link_to 'テーマ名変更', class: 'more__list__change-theme'
      %li
        = link_to '削除', class: 'more__list__delete'
.theme
  .more
    .more__image
      = image_tag 'arrow_top.png'
    %ul.more__list#pop
      %li
        = link_to 'テーマ名変更', class: 'more__list__change-theme'
      %li
        = link_to '削除', class: 'more__list__delete'
.theme
  .more
    .more__image
      = image_tag 'arrow_top.png'
    %ul.more__list#pop
      %li
        = link_to 'テーマ名変更', class: 'more__list__change-theme'
      %li
        = link_to '削除', class: 'more__list__delete'
.theme
  .more
    .more__image
      = image_tag 'arrow_top.png'
    %ul.more__list#pop
      %li
        = link_to 'テーマ名変更', class: 'more__list__change-theme'
      %li
        = link_to '削除', class: 'more__list__delete'
.theme
  .more
    .more__image
      = image_tag 'arrow_top.png'
    %ul.more__list#pop
      %li
        = link_to 'テーマ名変更', class: 'more__list__change-theme'
      %li
        = link_to '削除', class: 'more__list__delete'
.theme
  .more
    .more__image
      = image_tag 'arrow_top.png'
    %ul.more__list#pop
      %li
        = link_to 'テーマ名変更', class: 'more__list__change-theme'
      %li
        = link_to '削除', class: 'more__list__delete'
.theme
  .more
    .more__image
      = image_tag 'arrow_top.png'
    %ul.more__list#pop
      %li
        = link_to 'テーマ名変更', class: 'more__list__change-theme'
      %li
        = link_to '削除', class: 'more__list__delete'

app/views/themes/_theme_form.html.haml
.theme-form__field
  .theme-form__field--left
    Theme
  %textarea.theme-form__field--right

.theme-form__field.clearfix
  .theme-form__field--left
    Avatar
  %textarea.theme-form__field--right

.theme-form__field.clearfix
  .theme-form__field--left
    Add member
  %textarea.theme-form__field--right{placeholder: "Please enter the username you want to add"}

.theme-form__field.clearfix
  .theme-form__field--left
    Member
  .theme-form__field--right

= link_to "戻る", themes_path

app/views/themes/index.html.haml
.theme_contents
  = link_to "ブログのテーマを作成する", new_theme_path, class: "theme_contents__header"
  .themes
    = render partial: "theme"

app/views/themes/new.html.haml
.new-theme
  %h1 Create a blog theme
  = render partial: 'theme_form'

app/views/todos/_todo.html.haml
%li.todo
  %form{ action: "#" }
    %input.todo__check-btn{ id: "#{todo.id}", type: "checkbox"}
    %label.todo__text-content#text{ for: "#{todo.id}", id: "text" }
      = todo.content
    %button.todo__delete-btn.btn-text-3d
      = link_to "削除", todo_path(todo.id), method: :delete
      

app/views/todos/index.html.haml
.todo_contents
  %ul.todos
    = render partial: "todo", collection: @todos
= form_for @todo, html: { class: 'post-form' } do |f| 
  = f.text_field :content, class: 'post-form__text-field'
  = f.submit class: 'post-form__submit'